### ISSUE TITLE
Running Error @ Docker

### ISSUE THREAD

**Issue by attacker34** [codingo/crithit#4]
Hi @codingo  Just tried to run it via Docker and getting this Error:

```

docker run -v $(pwd):/input -t crithit -w  /input/dict.txt -t /input/hostnames.txt          
[2020-03-30 15:20:45.384] [error] [-] Unable to open the target list


docker run -v $(pwd):/input -t crithit -w  /input/dict.txt -T host.com
[2020-03-30 15:21:41.117] [error] [-] Unable to open filename containing the word list
failed to resize tty, using default size


```

**Comment by vortexau** [comment]
Hi @attacker34 - I contributed the Dockerfile, so I'm responding for @codingo. 

I'm not having the same issue, so it looks like your `dict.txt` and `hostnames.txt` aren't present in the directory you're running the Docker command from. Make sure the files named `dict.txt` and `hostnames.txt` are in the directory you run the command from:

```
# vortex @ vortex in ~/Projects/crithit on git:master x [12:13:05] 
$ ls -la | grep txt
-rw-r--r--  1 vortex vortex    10 Mar 31 12:11 dict.txt
-rw-r--r--  1 vortex vortex    10 Mar 31 12:11 hostnames.txt

# vortex @ vortex in ~/Projects/crithit on git:master x [12:13:15] 
$ docker run -v $(pwd):/input -t crithit -w /input/dict.txt -T host.com # Works OK.
https://host.com/test.php, test.php, 301

# vortex @ vortex in ~/Projects/crithit on git:master x [12:13:19] 
$ docker run -v $(pwd):/input -t crithit -w /input/nonexistant.txt -T host.com
[2020-03-31 01:43:23.167] [error] [-] Unable to open filename containing the word list

# vortex @ tatooine in ~/Projects/crithit on git:master x [12:13:23] 
$ docker run -v $(pwd):/input -t crithit -w /input/dict.txt -t /input/nonexistant.txt
[2020-03-31 01:46:02.535] [error] [-] Unable to open the target list
```

**Comment by attacker34** [comment]
Hi @vortexau I specially put the files in that directory. Even also tried to create dir named "input" and put the dict.txt and hostnames.txt in "input" DIR too,,,  But still its not working. 

One more thing to notice here is, Error does not say that "File not found" but it says:

```
[error] [-] Unable to open filename containing the word list
failed to resize tty, using default size

```

**Comment by vortexau** [comment]
Yep - that's the message that is printed when the file does not exist, or can't be read as outlined in my example above.

As above I can't replicate the issue, so step through by checking permissions of the file and ensure it can be read by other users.

**Comment by attacker34** [comment]
Hi @vortexau  I've just installed it again and its working now... Thanks. 
There is no kill switch like i tried to stop the process by ctrl+c but its not working..  Please show "Response Size" with Status Codes(200,301,401) ...
